### ISSUE TITLE
imagemagick install doesn't work anymore

### ISSUE THREAD

**Issue by lazytesting** [bdukes/Chocolatey-Packages#11]
The 'choco install imagemagick' is not working anymore.

It's trying to download: 
http://www.imagemagick.org/download/binaries/ImageMagick-6.9.3-1-Q16-x64-dll.exe
but that version is not on the server anymore.

I see that the 6.9.3.2 version is the latest version (and IM doesn't provide older binaries).
http://www.imagemagick.org/download/binaries/ImageMagick-6.9.3-2-Q16-x64-dll.exe

**Comment by bdukes** [comment]
Looks like the mirror that the package was using for old binaries has stopped serving ImageMagick.  I've created a 6.9.3-2 package which points to a new backup mirror.

Hope it helps.

**Comment by lazytesting** [comment]
Thanks @bdukes for your quick reply. I tested it and the package is working again.
