### ISSUE TITLE
ImageMagick install does not work anymore

### ISSUE THREAD

**Issue by alirazeen** [bdukes/Chocolatey-Packages#12]
It appears that the ImageMagick version has been updated to 7.0.2 from 7.0.1-5 and the old binary URL [www.imagemagick.org/download/binaries/ImageMagick-7.0.1-5-Q16-x64-dll.exe](http://www.imagemagick.org/download/binaries/ImageMagick-7.0.1-5-Q16-x64-dll.exe) does not work anymore. The new URL is [www.imagemagick.org/download/binaries/ImageMagick-7.0.2-0-Q16-x64-dll.exe](http://www.imagemagick.org/download/binaries/ImageMagick-7.0.2-0-Q16-x64-dll.exe).

**Comment by bdukes** [comment]
I've updated the package to 7.0.2-1 (see ef2f595), it's now in moderation
