### ISSUE TITLE
LastPass out of date

### ISSUE THREAD

**Issue by sxmanton** [bdukes/Chocolatey-Packages#19]
LastPass is now on v4.1.54 and the hash has changed again

Download of lastpass_x64.exe (29.3 MB) completed.
Error - hashes do not match. Actual value was 'DEBF0B5817DE3AE49FEDB882CDF1E4F28B3D92D47964152714233A8C217E8359'.

**Comment by bdukes** [comment]
@sxmanton fixed by e09637f, thanks!
