### ISSUE TITLE
Imagemagick fails to install

### ISSUE THREAD

**Issue by bazzilic** [bdukes/Chocolatey-Packages#22]
Hello,

Latest Imagemagick v7.0.8.16 fails to install with this error message:

![image](https://user-images.githubusercontent.com/1805832/50269904-cd5d5080-046a-11e9-8ee1-89e169d7e896.png)

**Comment by bdukes** [comment]
I'm not able to reproduce this issue (I tried installing 7.0.8.15 and upgrading), and `WindowsTerminal` (from the error message) doesn't appear in the install script.  Can you provide any further details that might help track this down?  Thanks!

**Comment by altimmons** [comment]
Likely the user was using a preview (at that point very early preview) build of windows terminal.  With no others I think its safe to close.   The early windows terminal had many many issues, as you'd expect from preview builds- it would have been early alpha then, I played with it and it was unusable until around 6mo ago. its good now.

**Comment by bazzilic** [comment]
> Likely the user was using a preview (at that point very early preview) build of windows terminal
Nope, I wasn't. This is ConEmu. Anyway, this issue is no longer present.

> and WindowsTerminal (from the error message) doesn't appear in the install script
Yeah, I know, that's the first thing I looked for. Sorry I didn't provide more details or a log back then. Must have missed the comment.
