### ISSUE TITLE
ImageMagick Packages failing package-validator

### ISSUE THREAD

**Issue by gep13** [bdukes/Chocolatey-Packages#29]
All the ImageMagick packages seem to link to here:

http://git.imagemagick.org/repos/ImageMagick

For the Project Source Url.  This Url doesn't seem to go anywhere, and as a result, the new package versions are failing a new package-validator rule that was added.

@bdukes are you in a position to fix these Url's?

**Comment by bdukes** [comment]
I've updated those URLs, thanks!

**Comment by gep13** [comment]
@bdukes that is great, thank you!  Will new packages automatically be pushed to include those changes?

**Comment by bdukes** [comment]
They're being pushed now

**Comment by gep13** [comment]
@bdukes I just wanted to touch base about this again...

Looking this morning I see that one package version has been corrected:

![image](https://user-images.githubusercontent.com/1271146/71879971-36bc0a00-3127-11ea-8359-8f36cbf8e1ff.png)

But the others remain in a Waiting For Maintainer state.  What would you like to do with these package versions?  Should we reject them, or are you in a position to fix these package versions as well?

**Comment by bdukes** [comment]
I pushed a couple more fixed versions, but didn't have all of them readily available, so I'm fine with those older versions becoming rejected.  Thanks @gep13!

**Comment by gep13** [comment]
@bdukes sounds like a plan.  I will go through and reject any remaining package versions tomorrow morning.  Thanks

**Comment by gep13** [comment]
@bdukes I have been through and rejected the remaining package versions for each of the ImageMagick packages.  Let me know if you need any un-rejected.
