### ISSUE TITLE
ImageMagick, ImageMagick (Install), ImageMagick (Portable) release notes link is incorrect

### ISSUE THREAD

**Issue by user8446** [bdukes/Chocolatey-Packages#43]
Hi,

Just pointing out that on all 3 packages the release notes link incorrectly points to: https://www.imagemagick.org/script/changelog.php

The correct link is: https://github.com/ImageMagick/Website/blob/main/ChangeLog.md

Thank you

**Comment by bdukes** [comment]
This is an issue with the ImageMagick website (the package release notes point to https://www.imagemagick.org/script/changelog.php which currently redirects to https://github.com/ImageMagick/ImageMagick/blob/main/ChangeLog.md). I've opened https://github.com/ImageMagick/Website/pull/86 and https://github.com/ImageMagick/Website6/pull/5 to fix those redirects. Thanks!
