### ISSUE TITLE
New linqpad checksum...

### ISSUE THREAD

**Issue by corbob** [bdukes/Chocolatey-Packages#48]
It looks like the `linqpad7.install` package for 7.7.15 failed validation due to a [checksum error](https://gist.github.com/choco-bot/0b4526a4b7652d2ddb87176a31816736#file-install-txt-L2052), and has now been rejected on the Chocolatey Community Repository

**Comment by bdukes** [comment]
The checksum matches in my testing, I've resubmitted. Thanks!
