### ISSUE TITLE
Rustdesk new release

### ISSUE THREAD

**Issue by rjmalagon** [bdukes/Chocolatey-Packages#49]
Hi, I don't know if this is the correct place to ask. Sorry if not.
Rustdek has released 1.2.0 update and is very welcome if you update your Chocolatey packages.

I would gladly offer help if you need a hand keeping the packages current too.

**Comment by bdukes** [comment]
The Rustdesk team adjusted the naming convention (and packaging) of their installer, so the auto-updater was failing. I've pushed packages for 1.2.0.

I'm definitely open to pull requests if you see that it's falling behind in the future. Thanks!
