### ISSUE TITLE
Have you considered adding the necessary dotnet runtimes as dependencies?

### ISSUE THREAD

**Issue by jasonmcboyd** [bdukes/Chocolatey-Packages#56]
This is a question more than an issue. As the title asks, has this been considered?

As an example, when I install linqpad7 from Chocolatey and run it, I am immediately greeted by a screen prompting me to install the .Net 7 runtime. If the dotnet-7.0-runtime Chocolatey package were a dependency of linqpad7, it could be installed automatically.

Thanks.

**Comment by bdukes** [comment]
It's been considered, and I'm on the fence about it. It is relatively common for .NET runtimes to be installed outside of Chocolatey, so I try to only add dependencies if it totally doesn't work without the runtime _and_ it's clear which version of the runtime to install. In this case, I believe that LINQPad 7 can actually run in .NET 6-8, so requiring .NET 7 runtime may actually result in an install that isn't required or desired. I'm open to alternative ideas, but that's where I've landed so far. Thanks for the question!
